### ISSUE TITLE
[BUG] <title>4块A100（40G）不能全参数微调吗

### ISSUE THREAD

**Issue by xyw7** [QwenLM/Qwen-VL#105]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

4块40G A100全参数微调cuda out of mem

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.26 GiB (GPU 1; 39.59 GiB total capacity; 32.52 GiB already allocated; 5.48 GiB free; 32.59 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "finetune.py", line 360, in <module>
    train()
  File "finetune.py", line 353, in train
    trainer.train()
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/accelerate/accelerator.py", line 1280, in prepare
    result = self._prepare_deepspeed(*args)
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/accelerate/accelerator.py", line 1662, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 304, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1212, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1473, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 509, in __init__
    self.initialize_optimizer_states()
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 644, in initialize_optimizer_states
    self.optimizer.step()
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/raid/wangxy/anaconda3/envs/logo/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 155, in step
    state['exp_avg'] = torch.zeros_like(p.data)

是我使用有问题？还是我创建的json有问题 还是这种级别的A100根本无法全参数微调？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by tommy3266** [comment]
你微调创建的json是什么样的呀

**Comment by ShuaiBai623** [comment]
微调的样例可以参照readme的[Data preparation](https://github.com/QwenLM/Qwen-VL#data-preparation)，如果显存不够可以尝试lora，[Data preparation](https://github.com/QwenLM/Qwen-VL#data-preparation)

**Comment by xyw7** [comment]
> readme

我就是严格按照readme里给的格式建立的json，把user和assistant的内容替换了一下
![image](https://github.com/QwenLM/Qwen-VL/assets/58246533/5e5ab029-fc67-41ed-8937-c3bf0a8ed48c)

但貌似都没有开始训练 看报错到加载optimizer的地方就oom了 


> 微调的样例可以参照readme的[Data preparation](https://github.com/QwenLM/Qwen-VL#data-preparation)，如果显存不够可以尝试lora，[Data preparation](https://github.com/QwenLM/Qwen-VL#data-preparation)

所以想问一下全参数微调的成功案例都是用的什么卡 A100 80G？

**Comment by ShuaiBai623** [comment]
我们这边测试用的是A100 80G

**Comment by tommy3266** [comment]
> 我们这边测试用的是A100 80G

我这边有两个机器，都是A100、40G的，有办法全参数微调吗

**Comment by stomachacheGE** [comment]
> 我们这边测试用的是A100 80G

单台A100 80G就可以全参数微调吗？
