### ISSUE TITLE
[BUG] <title>如何实现单机多张gpu训练?现在的训练方式好像只能单机单卡训练.

### ISSUE THREAD

**Issue by tangyipeng100** [QwenLM/Qwen-VL#186]
如何实现单机多张gpu训练?现在的训练方式好像只能单机单卡训练.
我尝试将finetune_qlora_single_gpu.sh中改为:
```
export CUDA_DEVICE_MAX_CONNECTIONS=2
export CUDA_VISIBLE_DEVICES=0,1
```
训练会报错:
```
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "finetune.py", line 367, in <module>
    train()
  File "finetune.py", line 360, in train
    trainer.train()
  File "/home/lhs/anaconda3/envs/jarvis/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/lhs/anaconda3/envs/jarvis/lib/python3.8/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/lhs/anaconda3/envs/jarvis/lib/python3.8/site-packages/transformers/trainer.py", line 2693, in training_step
    self.accelerator.backward(loss)
  File "/home/lhs/anaconda3/envs/jarvis/lib/python3.8/site-packages/accelerate/accelerator.py", line 1979, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
AttributeError: 'NoneType' object has no attribute 'backward'

```

**Comment by tangyipeng100** [comment]
直接用分布式训练即可

**Comment by ZhengHanying** [comment]
请问如何指定多卡训练？一直报oom错误

**Comment by ybshaw** [comment]
> 直接用分布式训练即可

finetune的时候如何分布式，有相关代码吗
