### ISSUE TITLE
如何全参数微调

### ISSUE THREAD

**Issue by njucckevin** [QwenLM/Qwen-VL#205]
您好，想问应该如何进行全参数微调呢？需要的配置是什么？
尝试了sh finetune/finetune_ds.sh，batch_size为1，max_seq_len=768的情况下在单卡A100 80G上就会OOM。似乎在加载优化器的过程中就OOM了，这个情况正常吗？
```
Traceback (most recent call last):
  File "finetune.py", line 366, in <module>
    train()
  File "finetune.py", line 359, in train
    trainer.train()
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/accelerate/accelerator.py", line 1209, in prepare
    result = self._prepare_deepspeed(*args)
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/accelerate/accelerator.py", line 1582, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 304, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1231, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1559, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 362, in __init__
    self._setup_for_real_optimizer()
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 474, in _setup_for_real_optimizer
    self.initialize_optimizer_states()
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 1008, in initialize_optimizer_states
    self._optimizer_step(i)
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 934, in _optimizer_step
    self.optimizer.step()
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/cpfs01/user/chengkanzhi/.conda/envs/qwen/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 155, in step
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 3.77 GiB (GPU 0; 79.35 GiB total capacity; 66.07 GiB already allocated; 2.89 GiB free; 75.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by njucckevin** [comment]
或许单卡无法训练，必须多卡？

**Comment by ShuaiBai623** [comment]
全参数微调需要多卡，单卡显存不够

**Comment by yuanlisky** [comment]
> 全参数微调需要多卡，单卡显存不够

那需要多少显存呢，有估值吗？
