### ISSUE TITLE
[BUG] <title>qwen-vl-chat demo bug

### ISSUE THREAD

**Issue by LLH-Harward** [QwenLM/Qwen-VL#247]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1.modelscope demo问题：在modelscope的qwen-vl-plus demo中输入一张图片 然后输入请求“图片描述”  等到qwen-vl-plus回答完毕后 点击regenerate按钮 期望其重新生成图片描述 此时报错
<img width="1036" alt="微信图片_20240118001208" src="https://github.com/QwenLM/Qwen-VL/assets/78243429/48a72390-8aa2-4875-87af-126fed32f041">
<img width="1090" alt="微信图片_20240118001212" src="https://github.com/QwenLM/Qwen-VL/assets/78243429/b6fec411-2e98-4b7d-990b-f8da76bba4f1">
2. 本地运行demo问题：运行web_demo_mm.py文件 加载qwen-vl-chat-int4或qwen-vl-chat 首先输入一张图片 然后输入prompt“图片描述”  等到qwen-vl-plus回答完毕后 点击regenerate按钮 期望其重新生成图片描述 此时报错（同modelscope demo）
![image](https://github.com/QwenLM/Qwen-VL/assets/78243429/de351657-5fe1-408a-822b-7559b90b199e)

终端内容：
F:\Anaconda\python.exe D:\Qwen-VL-master\web_demo_mm.py 
2024-01-18 00:16:17,949 - modelscope - INFO - PyTorch version 2.1.1+cu118 Found.
2024-01-18 00:16:17,966 - modelscope - INFO - Loading ast index from D:\Mycache\ast_indexer
2024-01-18 00:16:18,329 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 27a9a55bf27aebc83a20c19c1c710270 and a total number of 946 components indexed
2024-01-18 00:16:21,597 - modelscope - WARNING - Using the master branch is fragile, please use it with caution!
2024-01-18 00:16:21,597 - modelscope - INFO - Use user-specified model revision: master
2024-01-18 00:16:23,257 - modelscope - WARNING - Using the master branch is fragile, please use it with caution!
2024-01-18 00:16:23,257 - modelscope - INFO - Use user-specified model revision: master
Loading checkpoint shards: 100%|██████████| 5/5 [01:09<00:00, 13.88s/it]
2024-01-18 00:17:42,584 - modelscope - WARNING - Using the master branch is fragile, please use it with caution!
2024-01-18 00:17:42,584 - modelscope - INFO - Use user-specified model revision: master
Running on local URL:  http://127.0.0.1:8000

To create a public link, set `share=True` in `launch()`.
User: 图片描述
Qwen-VL-Chat: 图中是一群学生在教室里坐着上课，口罩颜色不同，代表不同科目。
User: 图片描述
Qwen-VL-Chat: 图中是一群学生在教室里学习，他们戴着白色口罩，穿着不同颜色的外套。
Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "F:\Anaconda\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\Anaconda\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\Anaconda\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "F:\Anaconda\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "F:\Anaconda\lib\site-packages\gradio_client\utils.py", line 928, in traverse
    new_obj.append(traverse(item, func, is_root))
  File "F:\Anaconda\lib\site-packages\gradio_client\utils.py", line 928, in traverse
    new_obj.append(traverse(item, func, is_root))
  File "F:\Anaconda\lib\site-packages\gradio_client\utils.py", line 923, in traverse
    new_obj[key] = traverse(value, func, is_root)
  File "F:\Anaconda\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "F:\Anaconda\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "F:\Anaconda\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "F:\Anaconda\lib\site-packages\gradio\blocks.py", line 256, in move_resource_to_block_cache
    url_or_file_path = str(utils.abspath(url_or_file_path))
  File "F:\Anaconda\lib\site-packages\gradio\utils.py", line 919, in abspath
    if is_symlink or path == path.resolve():  # in case path couldn't be resolved
  File "F:\Anaconda\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "F:\Anaconda\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: "('C:\\Users\\714\\AppData\\Local\\Temp\\gradio\\9730da679ac60b9ac1afa4a1b5458a8f9cbfe6d3\\图片.jpg',)"

### 期望行为 | Expected Behavior

点击regenerate按钮 期望其重新生成图片描述

### 复现方法 | Steps To Reproduce

1. [进入](https://modelscope.cn/studios/qwen/Qwen-VL-Chat-Demo/summary)
2. 上传任意图片
3. 输入“图片描述”
4. 点击regenerate按钮 

### 运行环境 | Environment

```Markdown
- OS:win10
- Python:py39
- Transformers:4.36.2
- modelscope: 1.10.0
- PyTorch: 2.1.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): cu118
```

**Comment by zenjieli** [comment]
See my PR #283 .

**Comment by LLH-Harward** [comment]
Thanks, I'll check later

> See my PR #283 .
