### ISSUE TITLE
[BUG] 当device_map设置为auto时无法正常推理

### ISSUE THREAD

**Issue by lwh9346** [QwenLM/Qwen-VL#26]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行如下代码，开启`bf16`和`device_map="auto"`
``` python
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
import torch
torch.manual_seed(1234)
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True)

# 打开bf16精度，A100、H100、RTX3060、RTX3070等显卡建议启用以节省显存
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()

model.generation_config = GenerationConfig.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True)

query = tokenizer.from_list_format([
    {'image': 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'}, # Either a local path or an url
    {'text': '这是什么?'},
])
response, history = model.chat(tokenizer, query=query, history=None)
print(response)

response, history = model.chat(tokenizer, '框出图中击掌的位置', history=history)
print(response)
image = tokenizer.draw_bbox_on_latest_picture(response, history)
if image:
  image.save('1.jpg')
else:
  print("no box")
```
产生如下报错信息
```
(venv) PS D:\Python\Qwen-VL> python .\debug.py
Loading checkpoint shards: 100%|████████████| 10/10 [00:14<00:00,  1.47s/it]
Traceback (most recent call last):
  File "D:\Python\Qwen-VL\debug.py", line 16, in <module>
    response, history = model.chat(tokenizer, query=query, history=None)
  File "D:\cache\huggingface\modules\transformers_modules\Qwen\Qwen-VL-Chat\1fb8c15e1ad1d0d4d5a17b550776d28a3f7ef028\modeling_qwen.py", line 918, in chat
    outputs = self.generate(
  File "D:\cache\huggingface\modules\transformers_modules\Qwen\Qwen-VL-Chat\1fb8c15e1ad1d0d4d5a17b550776d28a3f7ef028\modeling_qwen.py", line 1031, in generate
    return super().generate(
  File "D:\Python\Qwen-VL\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Python\Qwen-VL\venv\lib\site-packages\transformers\generation\utils.py", line 1642, in generate
    return self.sample(
  File "D:\Python\Qwen-VL\venv\lib\site-packages\transformers\generation\utils.py", line 2724, in sample
    outputs = self(
  File "D:\Python\Qwen-VL\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Python\Qwen-VL\venv\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\cache\huggingface\modules\transformers_modules\Qwen\Qwen-VL-Chat\1fb8c15e1ad1d0d4d5a17b550776d28a3f7ef028\modeling_qwen.py", line 830, in forward
    transformer_outputs = self.transformer(
  File "D:\Python\Qwen-VL\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\cache\huggingface\modules\transformers_modules\Qwen\Qwen-VL-Chat\1fb8c15e1ad1d0d4d5a17b550776d28a3f7ef028\modeling_qwen.py", line 570, in forward
    images = self.visual.encode(images)
  File "D:\cache\huggingface\modules\transformers_modules\Qwen\Qwen-VL-Chat\1fb8c15e1ad1d0d4d5a17b550776d28a3f7ef028\visual.py", line 426, in encode
    return self(images)
  File "D:\Python\Qwen-VL\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Python\Qwen-VL\venv\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\cache\huggingface\modules\transformers_modules\Qwen\Qwen-VL-Chat\1fb8c15e1ad1d0d4d5a17b550776d28a3f7ef028\visual.py", line 398, in forward
    x = self.conv1(x)  # shape = [*, width, grid, grid]
  File "D:\Python\Qwen-VL\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Python\Qwen-VL\venv\lib\site-packages\accelerate\hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "D:\Python\Qwen-VL\venv\lib\site-packages\accelerate\hooks.py", line 290, in pre_forward
    return send_to_device(args, self.execution_device), send_to_device(
  File "D:\Python\Qwen-VL\venv\lib\site-packages\accelerate\utils\operations.py", line 151, in send_to_device
    return honor_type(
  File "D:\Python\Qwen-VL\venv\lib\site-packages\accelerate\utils\operations.py", line 83, in honor_type
    return type(obj)(generator)
  File "D:\Python\Qwen-VL\venv\lib\site-packages\accelerate\utils\operations.py", line 152, in <genexpr>
    tensor, (send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys) for t in tensor)
  File "D:\Python\Qwen-VL\venv\lib\site-packages\accelerate\utils\operations.py", line 167, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

### 运行环境 | Environment

```Markdown
- OS: Windows11
- Python: 3.10.9
- Transformers: 4.31.0和4.32.0都试过
- PyTorch: 2.0.1+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
- GPU: RTX4080
```

**Comment by ShuaiBai623** [comment]
There will be problems with the automatic model partition here, you can change the device_map to "cuda".

**Comment by lwh9346** [comment]
> There will be problems with the automatic model partition here, you can change the device_map to "cuda".

Then I get `CUDA out of memory`.

```
发生异常: OutOfMemoryError
CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 15.99 GiB total capacity; 15.09 GiB already allocated; 0 bytes free; 15.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  File "D:\Python\Qwen-VL\debug.py", line 8, in <module>
    model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cuda", trust_remote_code=True, bf16=True).eval()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 15.99 GiB total capacity; 15.09 GiB already allocated; 0 bytes free; 15.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by ShuaiBai623** [comment]
The current model requires about 23G of GPU memory, and we are working on the INT4 quantized model and will release it later.

**Comment by ShuaiBai623** [comment]
The Int4 quantized model for Qwen-VL-Chat, [Qwen-VL-Chat-Int4](https://huggingface.co/Qwen/Qwen-VL-Chat-Int4), is available. About 12G cost

**Comment by shadowboxx** [comment]
> There will be problems with the automatic model partition here, you can change the device_map to "cuda".

That is right ！ thanks
