### ISSUE TITLE
[BUG] q-lora  微调qwen-vl-chat-int4 报错

### ISSUE THREAD

**Issue by shadowboxx** [QwenLM/Qwen-VL#289]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

用q-lora微调，加载完基础模型qwen-vl-chat-int4， 报错 assert self.qweight.device.type == "cuda".

### 期望行为 | Expected Behavior

加载完模型后，开始微调训练

### 运行环境 | Environment

```Markdown
- OS: wsl ubuntu 22.04
- Python: 3.10
- Transformers: 4.32
- PyTorch: 2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

### 备注 | Anything else?

[2024-02-18 20:42:30,759] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loading attributes (e.g. disable_exllama, use_cuda_fp16) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 5/5 [01:30<00:00, 18.13s/it]
Traceback (most recent call last):
  File "/mnt/e/User/huyunliu/GitHub/Qwen-VL/finetune.py", line 370, in <module>
    train()
  File "/mnt/e/User/huyunliu/GitHub/Qwen-VL/finetune.py", line 301, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/huyunliu/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/home/huyunliu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3161, in from_pretrained
    model = quantizer.post_init_model(model)
  File "/home/huyunliu/.local/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 493, in post_init_model
    model = autogptq_post_init(model, use_act_order=self.desc_act)
  File "/home/huyunliu/AutoGPTQ/auto_gptq/modeling/_utils.py", line 489, in autogptq_post_init
    submodule.post_init(temp_dq=model.device_tensors[device])
  File "/home/huyunliu/AutoGPTQ/auto_gptq/nn_modules/qlinear/qlinear_exllamav2.py", line 170, in post_init
    assert self.qweight.device.type == "cuda"
AssertionError

**Comment by GuiQuQu** [comment]
我单卡微调qwen-vl-chat-int4也报错了，错误是说cpu不支持半精度，感觉是不是那个device_map设置的有问题，我看值是None，把模型放到cpu上了，只有ddp(WORLD_SIZE!=1)的情况下，device_map才有变化

**Comment by shadowboxx** [comment]
> 我单卡微调qwen-vl-chat-int4也报错了，错误是说cpu不支持半精度，感觉是不是那个device_map设置的有问题，我看值是None，把模型放到cpu上了，只有ddp(WORLD_SIZE!=1)的情况下，device_map才有变化

好像是这个问题，我把device_map改成 ‘cuda‘ 了，就可以

**Comment by LiMa-cas** [comment]
您好，请问qlora python qlora.py --model_name_or_path <path_or_name> 这个model是fp16的还是int4的？十分感谢！！！为什么fp16的能跑通但是int4的跑不了？
