### ISSUE TITLE
[BUG] <title>请问如何指定缓存目录？

### ISSUE THREAD

**Issue by sunmoon-1024** [QwenLM/Qwen-VL#307]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在很多高安全性的场景下，默认的缓存目录可能不会有写权限，会导致模型运行失败。请问有没有办法可以指定缓存目录？

Traceback (most recent call last):
File "/data/yard/workspace/finetune-qwen-llm/finetune/../finetune.py", line 12, in 
from deepspeed import zero
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/init.py", line 21, in 
from . import ops
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/init.py", line 13, in 
from . import transformer
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/init.py", line 7, in 
from .inference.config import DeepSpeedInferenceConfig
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/inference/init.py", line 7, in 
from ....model_implementations.transformers.ds_transformer import DeepSpeedTransformerInference
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/model_implementations/init.py", line 6, in 
from .transformers.ds_transformer import DeepSpeedTransformerInference
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py", line 17, in 
from deepspeed.ops.transformer.inference.triton.mlp import TritonMLP
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/init.py", line 10, in 
from .ops import *
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/ops.py", line 8, in 
import deepspeed.ops.transformer.inference.triton.matmul_ext as matmul_ext
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 428, in 
fp16_matmul = Fp16Matmul()
^^^^^^^^^^^^
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 177, in init
class._read_autotune_table()
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 411, in _read_autotune_table
TritonMatmul._read_autotune_table(class.name + "_2d_kernel", class._2d_kernel)
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 132, in _read_autotune_table
cache_manager = AutotuneCacheManager(cache_key)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/python3.11/lib/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 55, in init
os.makedirs(self.cache_dir, exist_ok=True)
File "", line 215, in makedirs
File "", line 215, in makedirs
File "", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/mm'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by sunmoon-1024** [comment]
解决了 设置TRITON_CACHE_DIR即可
