### ISSUE TITLE
evaluate_grounding.py测试报错json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by yihp** [QwenLM/Qwen-VL#333]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我在用用evaluate_grounding.py测试微调后的模型，测试数据集我采用的和微调数据格式一样，[
    {
        "id": "identity_0",
        "conversations": [
            {
                "from": "user",
                "value": "Picture 1: <img>/datasets/data_qwen/NIH_vg/images/test/00013118_008.png</img>\nOutline the location of the disease in the image."
            },
            {
                "from": "assistant",
                "value": "<ref>Atelectasis</ref><box>(225,547),(311,626)</box>"
            }
        ]
    }，
]
但是执行测试代码evaluate_grounding.py就报错如下：
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:18<00:00,  1.89s/it]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "evaluate_grounding.py", line 152, in <module>
    for _, (input_ids, attention_mask, bboxes,
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 643, in reraise
    raise RuntimeError(msg) from None
RuntimeError: Caught JSONDecodeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "evaluate_grounding.py", line 69, in __getitem__
    data = json.loads(self.datas[idx].strip())
  File "/opt/conda/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

### 期望行为 | Expected Behavior

能够正常进行测试

### 运行环境 | Environment

```Markdown
Python: 3.8
Transformers: 4.32.0
PyTorch: 2.0.0
```

**Comment by yihp** [comment]
已解决，测试代码是按行读的
