### ISSUE TITLE
evaluate_caption.py测试，已经下载好converted files数据，数据地址也对应上，但是No such file or directory: 'data/nocaps/val/0013ea2087020901.jpg' ，是需要下载images吗？

### ISSUE THREAD

**Issue by AlexMa0** [QwenLM/Qwen-VL#335]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior
初次尝试， 需要大家指点迷津，谢谢~
我在evaluate_caption.py测试格式是：
ds="nocaps"
checkpoint=/data/checkpoint/qwen/Qwen-VL-Chat
python -m torch.distributed.run
--nproc_per_node 1
--nnodes 1
--node_rank 0
--master_addr ${MASTER_ADDR:-127.0.0.1}
--master_port 12345
evaluate_caption.py
--checkpoint $checkpoint
--dataset $ds
--batch-size 8
--num-workers 2
数据集也已经下载好但是会出现找不到图片地址的情况，
Traceback (most recent call last):
  File "/data/checkpoint/qwen/Qwen-VL-Chat/eval_mm/evaluate_caption.py", line 143, in <module>
    pred = model.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/modeling_qwen.py", line 1058, in generate
    return super().generate(
  File "/root/conda/envs/llm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/conda/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1722, in generate
    return self.beam_sample(
  File "/root/conda/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 3350, in beam_sample
    outputs = self(
  File "/root/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/modeling_qwen.py", line 848, in forward
    transformer_outputs = self.transformer(
  File "/root/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/modeling_qwen.py", line 565, in forward
    images = self.visual.encode(images)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 422, in encode
    image = Image.open(image_path)
  File "/root/conda/envs/llm/lib/python3.9/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/nocaps/val/0013ea2087020901.jpg'

补充：
我按照Qwen-VL/eval_m/EVALUATION.md的说明下载了converted files。
并在evaluate_caption.py的ds_collections部分将地址已经设置为：/data/checkpoint/qwen/Qwen-VL-Chat/data/nocaps/nocaps_val.json。。但是报错的是data/nocaps/val/0013ea2087020901.jpg。下载好的nocaps文件夹下是没有val这个子文件。只有一个nocaps_val.json
是还要下载images吗？
image链接# download images from https://nocaps.org/download点进去是具体图片的信息：
"licenses": [],
    "info": {
        "url": "",
        "date_created": "2018/11/06",
        "version": "0.1",
        "description": "nocap validation dataset",
        "contributor": "",
        "year": 2018
    },
    "images": [
        {
            "height": 1024,
            "file_name": "0013ea2087020901.jpg",
            "width": 732,
            "coco_url": "https://s3.amazonaws.com/nocaps/val/0013ea2087020901.jpg",
            "open_images_id": "0013ea2087020901",
            "id": 0,
            "license": 0,
            "domain": "in-domain",
            "date_captured": "2018-11-06 11:04:33"
        },
        {
            "height": 768,
            "file_name": "0032257bf3cd56d0.jpg",
            "width": 1024,
            "coco_url": "https://s3.amazonaws.com/nocaps/val/0032257bf3cd56d0.jpg",
            "open_images_id": "0032257bf3cd56d0",
            "id": 1,
            "license": 0,
            "domain": "near-domain",
            "date_captured": "2018-11-06 11:04:33"
        },

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by AlexMa0** [comment]
我在evaluate_caption.py测试格式是：
ds="nocaps"
checkpoint=/data/checkpoint/qwen/Qwen-VL-Chat
python -m torch.distributed.run
--nproc_per_node 1
--nnodes 1
--node_rank 0
--master_addr ${MASTER_ADDR:-127.0.0.1}
--master_port 12345
evaluate_caption.py
--checkpoint $checkpoint
--dataset $ds
--batch-size 8
--num-workers 2
数据集也已经下载好但是会出现没有图片地址的报错

**Comment by PEFT2026** [comment]
hello,我也有这个问题，请问你怎么解决的呢？谢谢
