### ISSUE TITLE
[BUG] AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'

### ISSUE THREAD

**Issue by wudidaxuexue** [QwenLM/Qwen-VL#480]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

[INFO 10-10 17:19:51 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='merge-14000_int4', speculative_config=None, tokenizer='merge-14000_int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=merge-14000_int4, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, mm_processor_kwargs=None)
Traceback (most recent call last):
  File "vllm_python.py", line 8, in <module>
    llm = LLM(model=model_path,trust_remote_code=True)
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 214, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 564, in from_engine_args
    engine = cls(
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 299, in __init__
    self.tokenizer = self._init_tokenizer()
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 608, in _init_tokenizer
    return init_tokenizer_from_configs(
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 28, in init_tokenizer_from_configs
    return get_tokenizer_group(parallel_config.tokenizer_pool_config,
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 49, in get_tokenizer_group
    return tokenizer_cls.from_config(tokenizer_pool_config, **init_kwargs)
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 30, in from_config
    return cls(**init_kwargs)
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 23, in __init__
    self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer.py", line 153, in get_tokenizer
    raise e
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer.py", line 119, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 892, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2208, in from_pretrained
    return cls._from_pretrained(
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2442, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/.cache/huggingface/modules/transformers_modules/merge-14000_int4/tokenization_qwen.py", line 120, in __init__
    super().__init__(**kwargs)
  File "/home/.conda/envs/qwen_vllm/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 436, in __init__
    self._add_tokens(
  File "/home/.cache/huggingface/modules/transformers_modules/merge-14000_int4/tokenization_qwen.py", line 227, in _add_tokens
    if surface_form not in SPECIAL_TOKENS + self.IMAGE_ST:
AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 22.04
- Python:3.10.15
- Transformers:4.45.2 
- PyTorch:2.4.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

### 备注 | Anything else?

qwen-vl-chat 模型训练后量化后使用vllm 部署，会出现如上错误，但是如果用官方模型部署，则没有这个问题。 issus类似的问题及其操作都尝试了，不适用， 比如修改transformer的版本、固定显卡、修改super().__init__(**kwargs)的位置等。

**Comment by wudidaxuexue** [comment]
已解决。

**Comment by elesun2018** [comment]
请问如何实现vllm 部署qwen-vl-chat 模型

**Comment by wudidaxuexue** [comment]
> 请问如何实现vllm 部署qwen-vl-chat 模型

参考：https://docs.vllm.ai/en/latest/models/vlm.html

**Comment by cyz6668** [comment]
请问这个问题如何解决
