### ISSUE TITLE
💡 [REQUEST] - <colab在线体验报错，因为仓库变更>

### ISSUE THREAD

**Issue by LOGIC-10** [QwenLM/Qwen-VL#79]
报错如下

2023-09-14 05:53:43,421 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-14 05:53:43,422 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2023-09-14 05:53:43,422 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-09-14 05:53:43,423 - modelscope - INFO - No valid ast index found from /root/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2023-09-14 05:53:43,474 - modelscope - INFO - Loading done! Current index file version is 1.9.0, with md5 a00f3c503d31dd92ee75c9eaa69d073b and a total number of 921 components indexed
2023-09-14 05:53:45.540126: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-09-14 05:53:46,849 - modelscope - ERROR - Authentication token does not exist, failed to access model qwen/Qwen-VL-Chat-Int4 which may not exist or may be                 private. Please login first.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/errors.py", line 81, in handle_http_response
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://www.modelscope.cn/api/v1/models/qwen/Qwen-VL-Chat-Int4/revisions?EndTime=1694670826

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/app.py", line 244, in <module>
    main()
  File "/content/app.py", line 238, in main
    model, tokenizer = _load_model_tokenizer(args)
  File "/content/app.py", line 52, in _load_model_tokenizer
    model_dir = snapshot_download(model_id, revision=args.revision)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/snapshot_download.py", line 96, in snapshot_download
    revision = _api.get_valid_revision(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/api.py", line 479, in get_valid_revision
    revisions = self.list_model_revisions(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/api.py", line 433, in list_model_revisions
    handle_http_response(r, logger, cookies, model_id)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/errors.py", line 88, in handle_http_response
    raise HTTPError('Response details: %s' % message) from error
requests.exceptions.HTTPError: Response details: {'Code': 10010200001, 'Message': '获取模型版本失败，信息：获取模失败', 'RequestId': '2d264083-e2a7-483a-b1ce-501ec3f24c66', 'Success': False}

**Comment by agoor97** [comment]
I have the same problem

**Comment by chigkim** [comment]
Same problem.

**Comment by lmc2000** [comment]
Same problem.
