### ISSUE TITLE
[BUG]AssertionError: Only Support Self-Attention Currently

### ISSUE THREAD

**Issue by summerbuild** [QwenLM/Qwen-VL#91]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

启动LORA微调，将ds_config_zero3.json的
```
"zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",--->修改为cpu
            "pin_memory": true
        },
        "offload_param": {
            "device": "none",
            "pin_memory": true
        },
```
报AssertionError: Only Support Self-Attention Currently错误

### 期望行为 | Expected Behavior

正常训练

### 复现方法 | Steps To Reproduce
```
Traceback (most recent call last):
  File "/home/jovyan/Qwen-VL/finetune.py", line 361, in <module>
Traceback (most recent call last):
  File "/home/jovyan/Qwen-VL/finetune.py", line 361, in <module>
    train()
  File "/home/jovyan/Qwen-VL/finetune.py", line 354, in train
    trainer.train()
  File "/opt/conda/lib/python3.9/site-packages/transformers/trainer.py", line 1553, in train
    train()
  File "/home/jovyan/Qwen-VL/finetune.py", line 354, in train
    trainer.train()
  File "/opt/conda/lib/python3.9/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.9/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/trainer.py", line 2679, in training_step
    return inner_training_loop(
  File "/opt/conda/lib/python3.9/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    loss = self.compute_loss(model, inputs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/trainer.py", line 2704, in compute_loss
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/trainer.py", line 2679, in training_step
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1801, in forward
    loss = self.compute_loss(model, inputs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/trainer.py", line 2704, in compute_loss
    loss = self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/modeling_qwen.py", line 848, in forward
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    ret_val = func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1801, in forward
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/modeling_qwen.py", line 565, in forward
    images = self.visual.encode(images)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 426, in encode
    return self(images)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    loss = self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 407, in forward
    x = self.transformer(x)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/peft/peft_model.py", line 918, in forward
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 328, in forward
    x = r(x, attn_mask=attn_mask)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    return self.base_model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 295, in forward
    x = q_x + self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 283, in attention
    return self.attn(q_x, k_x, v_x, attn_mask=attn_mask)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/modeling_qwen.py", line 848, in forward
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 192, in forward
    assert query is key, 'Only Support Self-Attention Currently'
AssertionError: Only Support Self-Attention Currently
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/modeling_qwen.py", line 565, in forward
    images = self.visual.encode(images)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 426, in encode
    return self(images)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 407, in forward
    x = self.transformer(x)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 328, in forward
    x = r(x, attn_mask=attn_mask)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 295, in forward
    x = q_x + self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 283, in attention
    return self.attn(q_x, k_x, v_x, attn_mask=attn_mask)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/visual.py", line 192, in forward
    assert query is key, 'Only Support Self-Attention Currently'
AssertionError: Only Support Self-Attention Currently
```

### 运行环境 | Environment

```Markdown
- OS:Ubuntu20.04
- Python:3.9.16
- Transformers:
- PyTorch:1.13
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.6
```

**Comment by BoyaWu10** [comment]
I get the same problem when running `finetune_ds.sh` with `---deepspeed finetune/ds_config_zero3.json` and `--fp16 True`.

**Comment by supermancmk** [comment]
I also get the same problem when running finetune_ds.sh with ---deepspeed finetune/ds_config_zero3.json and --fp16 True and V100 .

**Comment by supermancmk** [comment]
Do you have solved this problem?

**Comment by Muttermal** [comment]
I get the same problem. Is there a solution?

**Comment by Muttermal** [comment]
> I get the same problem. Is there a solution?

The source of the problem is line 192 of the code`visual.py`:
```python
assert query is key, 'Only Support Self-Attention Currently'
```
The problem was solved when I changed the code to this:
```python
assert torch.allclose(query, key), 'Only Support Self-Attention Currently'
```
I guess there might be a precision problem that causes `query` and `key` to be unequal

**Comment by Fake10086** [comment]
Is there a way to change zero3 to zero3_offload?

**Comment by aikedaerC** [comment]
I still met this problem in A800
```
--> [192]/home/aikedaer/mydata/LVLMs/Qwen-VL/~/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-VL-Chat/f57cfbd358cb56b710d963669ad1bcfb44cdcdd8/visual.py:192)     assert torch.allclose(query, key), 'Only Support Self-Attention Currently'

```

**Comment by hao-xyz** [comment]
> I still met this problem in A800
> 
> ```
> --> [192]/home/aikedaer/mydata/LVLMs/Qwen-VL/~/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-VL-Chat/f57cfbd358cb56b710d963669ad1bcfb44cdcdd8/visual.py:192)     assert torch.allclose(query, key), 'Only Support Self-Attention Currently'
> ```

hi, have solved this problem?

**Comment by mokby** [comment]
same issue here

**Comment by andyjiang1116** [comment]
just delete the L192 line `assert query is key, 'Only Support Self-Attention Currently'`。
It works when modify original downloaded model file in  `home/.cache/modelscope/hub/qwen/Qwen-VL/visual.py`. But if you modify the cached file in `home/.cache/huggingface/modules/transformers_modules/Qwen-VL/visual.py`, it won't work
