### ISSUE TITLE
Finetune LORA takes more memory usage for ds than single GPU

### ISSUE THREAD

**Issue by Jo-Pan** [QwenLM/Qwen-VL#92]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I can train with `finetune_lora_single_gpu.sh` properly. However, on the same device, I am not able to train with `finetune_lora_ds.sh`. The behavior is similar when I set GPUS_PER_NODE=1 and GPUS_PER_NODE=2. I also tried setting --per_device_train_batch_size to 1.  Everything works fine till model.train(). Seem like when it runs optimizer, the memory usage bumps quickly from ~22000MB to ~44000MB. Then it max out the memory usage. 

### Output from nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:01:00.0 Off |                  Off |
| 30%   56C    P8    38W / 300W |     10MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    On   | 00000000:41:00.0 Off |                  Off |
| 30%   46C    P8    21W / 300W |    210MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
```

### Logs from running finetune_lora_ds.sh
```
Loading checkpoint shards: 100%|██████████| 10/10 [00:06<00:00,  1.57it/s]
Loading data...
Formatting inputs...Skip in lazy mode
start training. LINE 352
Rank: 0 partition count [1] and sizes[(2601517056, False)] 
Traceback (most recent call last):
  File "/home/jopan/Projects/Qwen-VL/finetune.py", line 365, in <module>
    train()
  File "/home/jopan/Projects/Qwen-VL/finetune.py", line 358, in train
    trainer.train()
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/accelerate/accelerator.py", line 1280, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/accelerate/accelerator.py", line 1662, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 303, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1213, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1467, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 516, in __init__
    self.initialize_optimizer_states()
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 651, in initialize_optimizer_states
    self.optimizer.step()
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 155, in step
    state['exp_avg'] = torch.zeros_like(p.data)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.69 GiB (GPU 0; 47.54 GiB total capacity; 39.91 GiB already allocated; 6.69 GiB free; 39.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1395587) of binary: /home/jopan/anaconda3/envs/deepspeed/bin/python
Traceback (most recent call last):
  File "/home/jopan/anaconda3/envs/deepspeed/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-22_15:56:19
  host      : serc305
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1395587)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Output from ds_report
```
[2023-09-22 16:02:11,621] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1
deepspeed install path ........... ['/home/jopan/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.3, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
shared memory (/dev/shm) size .... 16.00 GB
```

### finetune_lora_ds.sh (only w. little modification)
```
#!/bin/bash
export NCCL_P2P_DISABLE=1
# export CUDA_DEVICE_MAX_CONNECTIONS=1
export CUDA_VISIBLE_DEVICES=0,1
DIR=`pwd`

GPUS_PER_NODE=1
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

MODEL="bibimbap/Qwen-VL-Chat"
# MODEL="Qwen/Qwen-VL-Chat" #"Qwen/Qwen-VL-Chat"/"Qwen/Qwen-VL"  Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="./dataset/easy_2rnd.json"
# OUTPUT_DIR="outputs/easy_2rnd"
OUTPUT_DIR='tmp'

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --fix_vit True \
    --output_dir $OUTPUT_DIR \
    --num_train_epochs 20 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 2048 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed finetune/ds_config_zero2.json
```
### 期望行为 | Expected Behavior

Train with `finetune_lora_ds.sh` on the same device.

### 复现方法 | Steps To Reproduce

Conda environment can be replicated by
```
conda env create -n deepspeed -f environment.yml --force
```

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04.5 LTS
- Python: 3.10
- Transformers: 4.32.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
```

**Comment by summerbuild** [comment]
试了，单卡A6000，zero2+卸载到内存才能跑起来，34G显存+58G内存才能跑起来
![20230925-192455](https://github.com/QwenLM/Qwen-VL/assets/5990736/3f2124e6-782a-4503-9d25-949323b7f8d5)

**Comment by Jo-Pan** [comment]
@summerbuild 谢谢！想请问一下您这是int4吗？我用Int4，cpu跟您差不多大（~150GB。
我双卡跑起来了：
- qlora_ds.sh
- fp16
- 没有用offload to cpu。


但我如果offload 到cpu就会直接给我卡退server，试了两三次都这样。如果我用Lora也是会要么oom要么卡退。我能看看您的ds_config 和finetune.sh吗？谢谢。

```
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:01:00.0 Off |                  Off |
| 74%   87C    P2   250W / 300W |  48225MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    On   | 00000000:41:00.0 Off |                  Off |
| 69%   86C    P2   247W / 300W |  48425MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
```
